### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by devinhalladay** [devinhalladay/spotio#10]
Just creating an issue here so we have a place to talk about Linux support; it should theoretically be a simple porting process.

**Comment by devinhalladay** [comment]
@sandervankasteel any chance you've had a bit of time to look into this?

**Comment by sandervankasteel** [comment]
@devinhalladay Yes I did, it isn't that hard! I want to finish it, this weekend.

**Comment by devinhalladay** [comment]
Great, thank you so much! I'm off to bed because it's 3am here but I'll check in on all the other issues in the morning. Thank you for all your help; I think you deserve an official recognition in the site/readme (along with Cole for his new icon design) :)

**Comment by slash686** [comment]
@sandervankasteel, Hey, do you need some help with this?

**Comment by sandervankasteel** [comment]
@slash686 I could use some help with testing because I'm porting it on Arch and double testing on Debian and Ubuntu. But I could always use some extra test machines

**Comment by sandervankasteel** [comment]
Spotio on Linux is a fact!! :D 

![screenshot from 2016-08-28 20-03-48](https://cloud.githubusercontent.com/assets/17492906/18035688/c8436dfe-6d5a-11e6-8e87-65445fc6a950.png)

I just need to smooth out some details @devinhalladay and then I will have a pull request for you!

**Comment by devinhalladay** [comment]
Omg yay!!! You rock!!!! Can't wait to share this with everyone :) I'm gonna edit the site and readme and give you soooo much credit for this

**Comment by mjgiarlo** [comment]
🍻

**Comment by sandervankasteel** [comment]
Pull request is standing by at #22

**Comment by devinhalladay** [comment]
You're a hero!!! Will review and merge tomorrow :)

**Comment by DrMajkrosoft** [comment]
Tried to run the script on Ubuntu 16.04.1, from the terminal I get this error code:

`setup-linux.sh: 6: [: x86_64: unexpected operator`
`setup-linux.sh: 14: setup-linux.sh: Bad substitution`

I know that the code says:

`if [ `uname -m` == 'x86_64' ]; then
  ARCH="amd64"
else
  ARCH="i386"
fi`

But I still wanted to give it a try since I saw that it can run on Arch.
Anyways, nice work you done there! :)

**Comment by mjgiarlo** [comment]
@DrMajkrosoft I'm curious... if you change `==` to `=` on line 6, does that fix you up?

**Comment by sandervankasteel** [comment]
@DrMajkrosoft which shell are you using ? Because I've tested it with bash, and I had no problems. So if you don't use bash, that's also something you can try.

**Comment by DrMajkrosoft** [comment]
Changing the operator from " == " to " = " fixed the issue on line 6, but I still get the line 14 error. I've tried to run the script from the terminal. I'm not really into programming, I only know the operators in C# and some basic programming, so you won't get much help from me, I'm just reporting the feedback from Ubuntu, I'm sure everything works fine on Arch.

**Comment by sandervankasteel** [comment]
@DrMajkrosoft I will test it tonight on a VM, see if I get the same results on Ubuntu 16.04.1

**Comment by d0od88** [comment]
Anecdotal, but I was also able to run the _setup-linux.sh_ without any issues on Ubuntu 16.04.1 using `./setup-linux` in the stock terminal app.

**Comment by DrMajkrosoft** [comment]
It works now! Thanks @d0od88  for the tip, turns out I was using bad commands, I used "sh setup-linux.sh" instead of "./setuo-linux.sh". I'm really sorry, everything's fine now, it works on Ubuntu 16.04.1. Thanks once again. 
![screenshot from 2016-08-31 14-46-59](https://cloud.githubusercontent.com/assets/12301022/18129221/05750080-6f8a-11e6-9c93-222708e2e9a6.png)

**Comment by sandervankasteel** [comment]
I did spot that the icon needs to be updated. 

@ColeTownsend could you send me the original icon files / upload it to this repo ? Then I can make sure the proper icons will be loaded on Linux.

**Comment by ColeTownsend** [comment]
@sandervankasteel I can't find the sketch file ATM, but I can export about every file type under the sun from my IconSlate file. 
[Spotio-Icon.zip](https://github.com/devinhalladay/spotio/files/447964/Spotio-Icon.zip)

**Comment by ViBE-HU** [comment]
I cannot install the application. It says that hdiutil is missing.

**Comment by sandervankasteel** [comment]
Thanks @ColeTownsend from what I can currently see from that file, that is everything I need.

**Comment by Pival81** [comment]
i don't know if somebody cares, but i made an aur package for this: https://aur.archlinux.org/packages/spotio/

**Comment by sandervankasteel** [comment]
@Pival81 thanks, you beat me to it ;)

**Comment by Pival81** [comment]
Wouldn't it better to have a custom .desktop file, instead of using the default Spotify one? I read that someone even made an icon for Spotio, maybe we can use that one.

**Comment by mjgiarlo** [comment]
:-1:

**Comment by sandervankasteel** [comment]
@Pival81 a few comments above, I already mentioned it : https://github.com/devinhalladay/spotio/issues/10#issuecomment-243784056

**Comment by Pival81** [comment]
@sandervankasteel oh, sorry :)

**Comment by sandervankasteel** [comment]
No problemo @Pival81.

@devinhalladay could you close this issue ? Since it's already addressed and currently only used for small-talk / "unrelated" stuff to Linux support
