### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by devinhalladay** [devinhalladay/spotio#11]
I'll begin looking into this later on this week. I have no idea if Spotify uses the same sort of skinning system in iOS but one can only hope.

If they do, skinning will be easy, but we will have to distribute the app via Cydia and AppAddict or iSignCloud in order to sign it on non-jailbroken devices. Are there any other methods to do this without jailbreaking?

**Comment by darkwinternight** [comment]
Not that I know of, you listed all 3. With Cydia, you could use Mobile Substrate to inject code into into the Spotify process, making the whole thing more seamless (and also safe[r] with updates).

**Comment by devinhalladay** [comment]
I don't know anything about Mobile Substrate programming (or any iOS programming at all, for that matter) so this is a bit out of my wheelhouse. If anyone wants to try taking that task on, I'm all for it.

Otherwise I'll try digging into the app when I get a chance early/mid- next month to see they also use CSS to style the mobile app, and if they do I'll do my best to get it working with iSignCloud. It's gonna be a hack no matter what which will *definitely* limit the mobile target audience, but I'm okay with that since there's really no other option unless we built our own 3rd-party iOS client
