### ISSUE TITLE
"Something broke. Failed to load error"

### ISSUE THREAD

**Issue by mixsta7** [devinhalladay/spotio#14]
After downloading I've found the only page that can load is the Browse page. After that any other tab or page will not load what so ever. I made sure my Mac Security setting were correct with downloads from anywhere. I can build up a queue from my phone but after that it's pretty much unresponsive. 
<img width="1280" alt="screen shot 2016-08-24 at 3 52 04 pm" src="https://cloud.githubusercontent.com/assets/21227494/17945645/c0bad96e-6a12-11e6-8c18-bd199cc029f0.png">
<img width="1280" alt="screen shot 2016-08-24 at 3 52 41 pm" src="https://cloud.githubusercontent.com/assets/21227494/17945664/d67914d2-6a12-11e6-8143-f36dc62ead4b.png">
<img width="1280" alt="screen shot 2016-08-24 at 3 52 41 pm" src="https://cloud.githubusercontent.com/assets/21227494/17945668/dbe522c6-6a12-11e6-834b-db39701528aa.png">
<img width="1280" alt="screen shot 2016-08-24 at 3 53 27 pm" src="https://cloud.githubusercontent.com/assets/21227494/17945690/ec837a38-6a12-11e6-8924-a70697947044.png">

**Comment by devinhalladay** [comment]
That's really odd, can you please try quitting all processes within activity monitor that are from spotify? I.e. Spotify.app, the Spotify web helper, etc

This is a new bug that hasn't been reported so I'll start there with the debug process

**Comment by sandervankasteel** [comment]
@mixsta7 which version of OS X / mac OS are you running ?

**Comment by sandervankasteel** [comment]
Since no reply from @mixsta7, we can close this one @devinhalladay ?
