### ISSUE TITLE
Cannot launch after first download

### ISSUE THREAD

**Issue by pauldandurand** [devinhalladay/spotio#15]
I downloaded the latest version 1.0.2 on August 24, 2016 on a Mac with the latest OS. Once unzipped and moved to the Applications folder, launching the app gives a message "Spotify.app is damaged and can't be opened. You should move it to the Trash." Attempted to re-download and open a couple times with the same issue.
![screen shot 2016-08-24 at 6 27 23 pm](https://cloud.githubusercontent.com/assets/20325803/17950304/6dbcd346-6a28-11e6-8a54-da5680e24dc7.png)

**Comment by pauldandurand** [comment]
My bad. Forgot to change security settings.

**Comment by devinhalladay** [comment]
@pauldandurand hopefully I'll be able to figure out a permanent fix for this soon, I still haven't been able to completely identify the cause of the bug

**Comment by sandervankasteel** [comment]
@pauldandurand just to able to diagnose this better, which version of OS X / mac OS are you running ?

**Comment by pauldandurand** [comment]
@sandervankasteel and @devinhalladay The version of my OS X is 10.11.6 (El Capitan)

**Comment by pauldandurand** [comment]
@devinhalladay does your Spotio app work the same as the Spotify app where it will occasionally play advertisement for those of us who have a free account? I ask because if I listen to Spotify via their web app, I never run into ads, whereas, if I listen to Spotify's own local Mac app, it does interrupt with ads. I stopped listening to their Mac app for that reason. I'm assuming your app would also play the ads since your app is a skinning solution. Is that correct?

Thanks,

Paul

**Comment by devinhalladay** [comment]
That's 100% correct. I styled the ads to fit the theme but that's it. I *could* in theory remove them but that would be just another reason for Spotify to come after me and take down this project

**Comment by pauldandurand** [comment]
Got. Thanks for the fast response. I shouldn't complain since I don't pay Spotify and I get free music. I used to pay for Pandora's yearly ad-free membership, but didn't use it that often. I will see if I will listen to Spotify more and maybe upgrade to ad free.
