### ISSUE TITLE
Differentiate between playable and unplayable songs

### ISSUE THREAD

**Issue by sandervankasteel** [devinhalladay/spotio#17]
For users (like me) who have enabled the setting "Show unavailable songs in playlists" there should be a visual differentiation between playable and unplayable songs. Currently they look the same.

![screen shot 2016-08-25 at 12 04 53](https://cloud.githubusercontent.com/assets/17492906/17965401/cba836a0-6abc-11e6-8844-c8485579d1f5.png)

Spotify's way of differentiation between playable and unplayable songs:
![screen shot 2016-08-25 at 12 09 02](https://cloud.githubusercontent.com/assets/17492906/17965407/d400943c-6abc-11e6-87af-8cf9d4e6e0b6.png)

The Taylor Swift song is unplayable in Spotify

**Comment by devinhalladay** [comment]
Got it, thanks for the bug report! Will fix this tonight.
