### ISSUE TITLE
PS4

### ISSUE THREAD

**Issue by devinhalladay** [devinhalladay/spotio#19]
Apparently, there's a Spotify app for PS4...is it feasible to port Spotio over since PS4 doesn't allow homebrew code? Maybe code injection from the hard drive? I've no experience with the PS4 operating system so I don't know about the development process but if anyone knows anything on the subject please post a comment here and we can feel out whether this is even feasible—even if it is, this would be far down the roadmap (first comes Windows, Linux, iOS, and Android)

**Comment by Fequois** [comment]
I'm not an expert on the subject but I'm fairly certain that the PS4 hasn't been cracked yet, so no, you won't be able to modify let alone sideload an app on it.

Also for iOS and Android apps you'll probably have to start from scratch using the official SDKs or someone will come bite your ass. 😞

**Comment by devinhalladay** [comment]
@Fequois that's what I thought, thanks! Figured I'd ask here since my friend mentioned it late last night and I was curious. I'll close this for now but if PS4 ever is cracked or there's a glitch to allow homebrew code then I'll be all over this.
