### ISSUE TITLE
alert saying app is damaged?

### ISSUE THREAD

**Issue by 1ca1** [devinhalladay/spotio#20]
![image](https://cloud.githubusercontent.com/assets/3229499/18031496/2c623e6e-6c98-11e6-9718-e1facd695055.png)

I keep getting this, after downloading from multiple browsers. 

¯\_(ツ)_/¯

I really appreciate you working on this, I love the design and am just excited to use it.

**Comment by devinhalladay** [comment]
Read the website/readme, or look through the existing issues. This is a known issue and has been solved with a temporary workaround and the solution is right on the site above the fold

**Comment by 1ca1** [comment]
dang, I see it now. thank you and sorry for the spam.

**Comment by devinhalladay** [comment]
Oh no! I'm sorry if I came across as salty haha, you caught me right when I had woken up. Thanks for closing the issue :) enjoy spotio! Make sure yore subscribed to the newsletter on the site because we have some major updates coming in the next few weeks
