### ISSUE TITLE
After restart back to black version

### ISSUE THREAD

**Issue by janfehlis** [devinhalladay/spotio#21]
When I restart Spotio the white UI is gone. Have to reinstall it to enjoy the nice UI. Any suggestions?

I am using OS X 10.11.6

**Comment by sandervankasteel** [comment]
Could you check the Spotify version for me ?

**Comment by devinhalladay** [comment]
You're on the right track sander I think it updated.

Your best bet is to redownload when it updates until we come up with an update system for spotify. Classes start today for me so I'm in the studio for 12 hours straight today and have long hours the rest of the week but I'll start looking into it this weekend

**Comment by devinhalladay** [comment]
Referencing #5 just for the sake of easy issue navigation

**Comment by sandervankasteel** [comment]
@devinhalladay that's what my thought as was well.

**Comment by devinhalladay** [comment]
Gonna close this for now. @janfehlis just go ahead and redownload spotio and subscribe to the mailing list so we can let you know when we release an update system!!
