### ISSUE TITLE
is there any other alternative for codesign on sierra OS X

### ISSUE THREAD

**Issue by barnai** [devinhalladay/spotio#27]
I used sketch pro, the trial is over
and now it asks even for the Sketch up Make for educational use license as well,
if there is any idea how can it be fixed it would be appreciated.

**Comment by devinhalladay** [comment]
Hey, I don't really understand your question here. This project is unrelated to Sketch.

**Comment by devinhalladay** [comment]
Can you clear up what you mean? If not I'm going to go ahead and close this issue

**Comment by barnai** [comment]
you might be close, since it not a project, Im just looking  for a guidemap  how to  master reset the trial version, because I can't even use for educational purposes the   Sketch up Make, and since it is running Sierra OS X codesign is not  works on it.

**Comment by sandervankasteel** [comment]
@devinhalladay since this issue isn't related to Spotio, I think we can close this one right ?

**Comment by devinhalladay** [comment]
Yeah this was a bizarre one, gonna go ahead and close
