### ISSUE TITLE
Spotio doesnt open 

### ISSUE THREAD

**Issue by amrthameen** [devinhalladay/spotio#29]
Hi, I cant seem to open Spotio, its telling me its damaged. Can you help? Thank you

**Comment by sandervankasteel** [comment]
@amrthameen is this on OS X ?

**Comment by amrthameen** [comment]
@sandervankasteel  OS Sierra

**Comment by sandervankasteel** [comment]
@amrthameen you need to resign your binary or disable GateKeeper on MacOS. Although disabling GateKeeper isn't a recommended method, it is the easiest to do. 

A while back I managed to resign the Spotio / Spotify application with my own keys; more info on this can be found here: https://github.com/devinhalladay/spotio/issues/23

**Comment by sandervankasteel** [comment]
@amrthameen did my comment resolve your issue ?

**Comment by devinhalladay** [comment]
I'm gonna go ahead and close this issue since it's inactive but if the issue persists just tag me and I can reopen it
