### ISSUE TITLE
Font suggestion

### ISSUE THREAD

**Issue by luki** [devinhalladay/spotio#31]
Not really an issue, but still.
Rdio used 'Whitney', good alternatives are:
 Museo Sans, FF Dagny, FF Meta, or Ratio

**Comment by devinhalladay** [comment]
Thanks for the suggestions! For the sake of sticking with Rdio's interface choices (because that's what Spotio is all about!) I'm going to keep the type set in Whitney for the future but if you'd like to try out another typeface feel free to fork this and compile your own version.

**Comment by luki** [comment]
@devinhalladay Won't this lead to legal issues, as Whitney is not free?

**Comment by devinhalladay** [comment]
I'm not too worried about it, if I get a DMCA I'll just switch it out for something else. But by that logic I couldn't use Museo of Dagny or Meta either; all of those require licenses
