### ISSUE TITLE
Does not launch on macOS 10.12.5

### ISSUE THREAD

**Issue by ghost** [devinhalladay/spotio#36]
![screen shot 2017-07-12 at 7 58 48 pm](https://user-images.githubusercontent.com/25700362/28144939-875afff0-673c-11e7-9c19-b2626d0f5b8e.png)

**Comment by thekevinboyle** [comment]
Under system preferences >> Security >> General >> Allow apps downloaded from anywhere

To enable this option you need to run the following:

From Terminal
sudo spctl --master-disable

**Comment by devinhalladay** [comment]
Hey, this is a known issue and something I'm unprepared to fix, as the time investment is too large for my availability.

@thekevinboyle thanks for jumping in with the workaround; for anyone else who stumbles into this issue I'd like to stress that I don't recommend this workaround, and that if you'd like Spotio to work I will always welcome contributors to this repo 🤓 

Closing as wontfix for now, until I have the time and energy (or contributors) to turn Spotio into a more full-fledged Spotify wrapper.
