### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by a-rock-lobster** [devinhalladay/spotio#39]
Sorry, not really an issue. I have been going through the live issues and can't quite tell if this is supposed to be functioning on mac atm… I haven't been able to get it working personally but I'm no whizz.

**Comment by devinhalladay** [comment]
Nope, I do not have the time to maintain this and Spotify did some new things with their update system that break the way I inject the custom CSS. I welcome any contributions & pull requests, but until I have time to revisit this (I likely never will), this project is dead in the water.
