### ISSUE TITLE
"Spotify" is damaged and can't be opened.

### ISSUE THREAD

**Issue by ghost** [devinhalladay/spotio#41]
Hi all,

From reading around, I'm under the impression that Spotio is no longer in development, and any errors aren't correctable.

That, just in case I'm being dense; I downloaded and unzipped, and when opening the app receive the error "Spotify" is damaged and can't be opened."

I take it the app is currently not useable?

**Comment by devinhalladay** [comment]
@Tomifonication correct, the app has been broken for some time and I do not have time to continue development on my own. Feel free to submit a PR to fix if you want to help out; I'm happy to take a moment to explain how everything works if the docs aren't sufficient.

Closing as wontfix.

**Comment by robni7** [comment]
I used `sudo xattr -cr [path to the unzipped Spotify.app]`. After this I could open the app. 
Hope this helps, regards, Robni7
